baseURL = 'https://foonly.dev/'
languageCode = 'en-uk'
title = 'foonly.dev'

[params]
  description = 'Personal site and blog'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30
